### ISSUE TITLE
Can't get this to work as an NPM Package

### ISSUE THREAD

**Issue by Bgallahue** [fen89/vscode-snippets#8]
Installed the NPM package into my project but none of the snippets are showing up in my .js or .ts files. Are there any additional steps I need to complete?

**Comment by fen89** [comment]
It's an VSCode Plugin, you can get it via the Extension Manager inside VCode:

![grafik](https://user-images.githubusercontent.com/4036376/99125406-42f4db80-2604-11eb-9a35-a0d7490c9bc8.png)

After installing the extensions all the snippets should be working.
